name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy-development:
    name: Deploy development
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Development
      docker-image: ghcr.io/AplinkosMinisterija/biip-hidro-web
      enable-sentry: true
      build-args: |
        NODE_ENV=development
        VITE_SENTRY_DSN=https://23a38fb0a5c44d1ea9451fedabcde5f1@sentry.biip.lt/17
