name: Deploy to Production
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-production:
    name: Deploy production
    uses: AplinkosMinisterija/reusable-workflows/.github/workflows/biip-deploy.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: Production
      docker-image: ghcr.io/AplinkosMinisterija/biip-hidro-web
      enable-sentry: true
      build-args: |
        NODE_ENV=production
        VITE_SENTRY_DSN=https://23a38fb0a5c44d1ea9451fedabcde5f1@sentry.biip.lt/17
